spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-107-22-238-112.compute-1.amazonaws.com:5432/ddtc37rhiol69m
    username: htlwzxeachuwje
    password: 6e79d2f061b3436a2ce2e5c2139c70df4149e3bd3f5f51cb67cc0a41f17ddc61
