CREATE TABLE IF NOT EXISTS public.tb_customer_api
(
    id int generated by default as identity ,
    uuid uuid DEFAULT uuid_generate_v4 () ,
    name varchar (255) ,
    email varchar (255)  UNIQUE,
    birth_date varchar (255),
    cpf varchar(255)  UNIQUE,
    gender varchar (255) ,
    CONSTRAINT tb_customer_api_pkey PRIMARY KEY (id)
);