--CREATE TABLE public.tb_customer_api (
--	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--	uuid uuid NULL DEFAULT uuid_generate_v4(),
--	"name" varchar(255) NULL,
--	email varchar(255) NULL,
--	birth_date varchar(255) NULL,
--	cpf varchar(255) NULL,
--	gender varchar(255) NULL,
--	main_address_id int4 NULL,
--	CONSTRAINT tb_customer_api_cpf_key UNIQUE (cpf),
--	CONSTRAINT tb_customer_api_email_key UNIQUE (email),
--	CONSTRAINT tb_customer_api_pkey PRIMARY KEY (id)
--);


-- public.tb_customer_api definition

-- Drop table

-- DROP TABLE public.tb_customer_api;

CREATE TABLE public.tb_customer_api (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	uuid uuid NULL DEFAULT uuid_generate_v4(),
	"name" varchar(255) NULL,
	email varchar(255) NULL,
	birth_date varchar(255) NULL,
	cpf varchar(255) NULL,
	gender varchar(255) NULL,
	CONSTRAINT tb_customer_api_cpf_key UNIQUE (cpf),
	CONSTRAINT tb_customer_api_email_key UNIQUE (email),
	CONSTRAINT tb_customer_api_pkey PRIMARY KEY (id)
);


-- public.tb_customer_api foreign keys

