CREATE TABLE IF NOT EXISTS public.tb_address_api
(
    id_address int generated by default as identity ,
    state varchar (255) ,
    city varchar (255)  UNIQUE,
    neighborhood varchar (255),
    zipCode varchar(255)  UNIQUE,
    number int  ,
    additionalInformation varchar (255),
    main
    CONSTRAINT tb_address_api_pkey PRIMARY KEY (id_address)
);
