CREATE TABLE public.tb_address_api (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	state varchar(255) NULL,
	city varchar(255) NULL,
	neighborhood varchar(255) NULL,
	zip_code varchar(255) NULL,
	"number" varchar(255) NULL,
	additional_information varchar(255) NULL,
	street varchar(255) NULL,
    main bool NULL,
    customer_id int4 NULL,
	CONSTRAINT tb_address_api_pkey PRIMARY KEY (id)
);


-- public.tb_address_api foreign keys

ALTER TABLE public.tb_address_api ADD CONSTRAINT tb_address_api_customer_id_fkey
FOREIGN KEY (customer_id) REFERENCES public.tb_customer_api(id)  ON DELETE cascade ON UPDATE cascade;

